### ISSUE TITLE
Exception: multichannel

### ISSUE THREAD

**Issue by bison--** [matrach/img2unicode#5]
It looks like that `skimage` has removed the `multichannel=True` parameter (again? found an old post that it was added in 0.14).  
https://github.com/matrach/img2unicode/blame/1eea995bf441e0f141312e9db0f1533d20b124f3/img2unicode/renderer.py#L72  
Tested a few versions of `skimage`, ~~but didn't work~~ works with `0.19.3`. Removing `multichannel=True` fixes the issue.

```
Traceback (most recent call last):
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\main.py", line 26, in <module>
    keep_running = main_menu()
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\main.py", line 16, in main_menu
    readToots.read_toots()
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\readToots.py", line 94, in read_toots
    display_toots(toots)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\readToots.py", line 67, in display_toots
    print_media_attachments(original_toot.get("media_attachments", []))
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\readToots.py", line 45, in print_media_attachments
    terminal_image.render_image(attachment["url"])
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\inc\TerminalImage.py", line 24, in render_image
    renderer.render_terminal(local_image, sys.stdout)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\venvs\venv3_10\lib\site-packages\img2unicode\renderer.py", line 108, in render_terminal
    chars, fgs, bgs = self.render_numpy(path_or_img, optimizer, **kwargs)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\venvs\venv3_10\lib\site-packages\img2unicode\renderer.py", line 112, in render_numpy
    img, chars, fgs, bgs = self.optimize(path_or_img, optimizer, **kwargs)
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\venvs\venv3_10\lib\site-packages\img2unicode\renderer.py", line 81, in optimize
    img = self._prepare_image(self._ensure_image(path_or_img))
  File "C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\venvs\venv3_10\lib\site-packages\img2unicode\renderer.py", line 73, in _prepare_image
    ims = skimage.filters.gaussian(ims, 1, multichannel=True)
TypeError: gaussian() got an unexpected keyword argument 'multichannel'

Process finished with exit code 1
```

**Comment by bison--** [comment]
Update: `skimage 0.19.3` throws a deprecated warning
```
C:\Users\Gamer\Documents\Projekte\coding\python\pyToot\venvs\venv3_10\lib\site-packages\img2unicode\renderer.py:72: FutureWarning: `multichannel` is a deprecated argument name for `gaussian`. It will be removed in version 1.0. Please use `channel_axis` instead.
  ims = skimage.filters.gaussian(ims, 1, multichannel=True)
```

**Comment by matrach** [comment]
Hi! Thanks for the heads up!
It should be fixed in 0.1a11 that I've just released.
Please let me know if it resolves your problem.

**Comment by bison--** [comment]
seems to work perfectly, thanks <3  
Thats the project BTW https://github.com/bison--/pyToot

**Comment by matrach** [comment]
> seems to work perfectly, thanks <3 Thats the project BTW https://github.com/bison--/pyToot

Cool! You may also consider using modern, mature projects like [rich](https://github.com/Textualize/rich) or [notcurses](https://github.com/dankamongmen/notcurses).
