### ISSUE TITLE
renderer TypeError: missing 1 required positional argument

### ISSUE THREAD

**Issue by bison--** [matrach/img2unicode#6]
Get the error with: `img2unicode.ExactGammaOptimizer()` and `img2unicode.BasicGammaOptimizer()`

```
img2unicode\renderer.py", line 82, in optimize
    chars, fgs, bgs = optimizer.optimize_chunk(img)
TypeError: BasicGammaOptimizer.optimize_chunk() missing 1 required positional argument: 'img_edges'
```

**Comment by RaczeQ** [comment]
@matrach I think this error can occur when the `Gamma` optimizer is paired with the normal `Renderer` instead of `GammaRenderer`
Without context it's hard to be sure, but it seems like the only explanation.

```python
>>> import img2unicode
>>> from pathlib import Path
>>> import sys
>>> renderer = img2unicode.Renderer()
>>> gamma_renderer = img2unicode.GammaRenderer()
>>> optimizer = img2unicode.FastGenericDualOptimizer("block")
>>> gamma_optimizer = img2unicode.ExactGammaOptimizer(charmask="ascii")
>>> obama_img = Path() / 'examples' / 'obama.jpg'
>>> renderer.render_terminal(obama_img, sys.stdout, optimizer)
... image
>>> renderer.render_terminal(obama_img, sys.stdout, gamma_optimizer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../img2unicode/img2unicode/renderer.py", line 107, in render_terminal
    chars, fgs, bgs = self.render_numpy(path_or_img, optimizer, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../img2unicode/img2unicode/renderer.py", line 111, in render_numpy
    img, chars, fgs, bgs = self.optimize(path_or_img, optimizer, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../img2unicode/img2unicode/renderer.py", line 82, in optimize
    chars, fgs, bgs = optimizer.optimize_chunk(img)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BasicGammaOptimizer.optimize_chunk() missing 1 required positional argument: 'img_edges'
>>> gamma_renderer.render_terminal(obama_img, sys.stdout, gamma_optimizer)
... image
>>> gamma_renderer.render_terminal(obama_img, sys.stdout, optimizer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../img2unicode/img2unicode/renderer.py", line 107, in render_terminal
    chars, fgs, bgs = self.render_numpy(path_or_img, optimizer, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../img2unicode/img2unicode/renderer.py", line 111, in render_numpy
    img, chars, fgs, bgs = self.optimize(path_or_img, optimizer, **kwargs)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../img2unicode/img2unicode/renderer.py", line 188, in optimize
    chars, fgs, bgs = optimizer.optimize_chunk(img_gray, img_edges, imgc)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseDualOptimizer.optimize_chunk() takes 2 positional arguments but 4 were given
```
